### ISSUE TITLE
Container does not have the cap_net_raw+p capability or setuid? capabilities.

### ISSUE THREAD

**Issue by sam1913** [nicolaka/netshoot#137]
I have deployed the container on to GKE cluster as a sidecar, here is the yaml file.
```
apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-netshoot
    labels:
        app: nginx-netshoot
spec:
  replicas: 1
  selector:
    matchLabels:
        app: nginx-netshoot
  template:
      metadata:
       labels:
          app: nginx-netshoot
      spec:
            containers:
            - name: nginx
              image: nginxinc/nginx-unprivileged
              ports:
                  - containerPort: 80
              securityContext:
                runAsNonRoot: true
                runAsUser: 100
                seccompProfile:
                  type: RuntimeDefault
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - NET_RAW
            - name: netshoot
              image: nicolaka/netshoot
              command: ["/bin/bash"]
              args: ["-c", "while true; do ping localhost; sleep 60;done"]
              securityContext:
                runAsNonRoot: true
                runAsUser: 100
                seccompProfile:
                  type: RuntimeDefault
                allowPrivilegeEscalation: false
                capabilities:
                  drop:
                  - NET_RAW
                  - NET_ADMIN
```
when I check the logs of the container,
I get the following,
```
ping: socktype: SOCK_RAW
ping: socket: Operation not permitted
ping: => missing cap_net_raw+p capability or setuid?
ping: socktype: SOCK_RAW
ping: socket: Operation not permitted
ping: => missing cap_net_raw+p capability or setuid?
```
Any ideas on how to overcome this, it looks like it needs packages of libcap/libcap_dev and also tcpdump command gives `operation not permitted` exception.

**Comment by thaJeztah** [comment]
Looks like the YAML you posted above drops those capabilities?

```yaml
capabilities:
  drop:
  - NET_RAW
  - NET_ADMIN
                
```
